# Generated by Django 5.2.8 on 2026-03-17 17:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Nom commun")),
                (
                    "scientific_name",
                    models.CharField(max_length=300, verbose_name="Nom scientifique"),
                ),
                (
                    "local_names",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Noms locaux"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=350, unique=True)),
                ("description", models.TextField(verbose_name="Description générale")),
                (
                    "morphology",
                    models.TextField(blank=True, verbose_name="Morphologie"),
                ),
                ("habitat", models.TextField(blank=True, verbose_name="Habitat")),
                (
                    "conservation_status",
                    models.CharField(
                        choices=[
                            ("common", "Commune"),
                            ("rare", "Rare"),
                            ("vulnerable", "Vulnérable"),
                            ("endangered", "En danger"),
                            ("critical", "Critique"),
                        ],
                        default="common",
                        max_length=20,
                    ),
                ),
                (
                    "traditional_uses",
                    models.TextField(blank=True, verbose_name="Usages traditionnels"),
                ),
                (
                    "therapeutic_properties",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Propriétés thérapeutiques",
                    ),
                ),
                (
                    "active_compounds",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Composés actifs"
                    ),
                ),
                (
                    "pharmacological_activities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Activités pharmacologiques",
                    ),
                ),
                (
                    "contraindications",
                    models.TextField(blank=True, verbose_name="Contre-indications"),
                ),
                ("chemical_formula", models.CharField(blank=True, max_length=200)),
                ("molecular_weight", models.FloatField(blank=True, null=True)),
                (
                    "sources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Sources bibliographiques",
                    ),
                ),
                ("gbif_id", models.CharField(blank=True, max_length=50)),
                ("plantnet_id", models.CharField(blank=True, max_length=50)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="plants/"),
                ),
                ("image_url", models.URLField(blank=True)),
                (
                    "is_premium",
                    models.BooleanField(default=False, verbose_name="Contenu premium"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Vérifié"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                ("views_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plante",
                "verbose_name_plural": "Plantes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlantFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("scientific_name", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Famille botanique",
                "verbose_name_plural": "Familles botaniques",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Région",
                "verbose_name_plural": "Régions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("free", "Gratuit"),
                            ("premium", "Premium"),
                            ("pro", "Professionnel"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Mensuel"), ("yearly", "Annuel")],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("price_fcfa", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("features", models.JSONField(default=list)),
                ("api_calls_limit", models.IntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Plan d'abonnement",
                "verbose_name_plural": "Plans d'abonnement",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("bio", models.TextField(blank=True)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("organisation", models.CharField(blank=True, max_length=200)),
                ("profession", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Gratuit"),
                            ("premium", "Premium"),
                            ("pro", "Professionnel"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("plan_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "api_key",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("api_calls_count", models.IntegerField(default=0)),
                ("api_calls_limit", models.IntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "db_table": "biomim_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("role", models.CharField(max_length=20)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("plant_refs", models.ManyToManyField(blank=True, to="biomim.plant")),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlantComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="biomim.plant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="plant",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plants",
                to="biomim.plantfamily",
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="regions",
            field=models.ManyToManyField(
                blank=True, to="biomim.region", verbose_name="Régions"
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("active", "Actif"),
                            ("expired", "Expiré"),
                            ("cancelled", "Annulé"),
                            ("failed", "Échoué"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "paygate_transaction_id",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "paygate_reference",
                    models.CharField(blank=True, max_length=200, unique=True),
                ),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("amount_paid", models.IntegerField(default=0)),
                ("currency", models.CharField(default="XOF", max_length=10)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="biomim.subscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement",
                "verbose_name_plural": "Abonnements",
                "ordering": ["-created_at"],
            },
        ),
    ]
